### ISSUE TITLE
NOASSERTION case lacks reasonable evidence

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#1014]
The following cases all have possible misidentified NOASSERTION finding. Little to no evidence could be found in any project file to confidently assign the project with NOASSERTION...

**rubygems/-/wareki/0.3.0**

CD: https://clearlydefined.io/definitions/gem/rubygems/-/wareki/0.3.0
GH: https://github.com/sugi/wareki/tree/77fcfe526b34d59c35fbeb5a24b23a6950709e9d

- All files identified correctly as BSD-2; also zero NOASSERTION files

**rubygems/-/uk_account_validator_auctionet/0.0.9**

CD: https://clearlydefined.io/definitions/gem/rubygems/-/uk_account_validator_auctionet/0.0.9
GH: https://github.com/barsoom/uk_account_validator/tree/626306429ac3205bfc92f98b98a0581f49da7cc6

- There is a gemspec package manager file in root that listed License as BSD-2 but identified as NOASSERTION

- Zero NOASSERTION files

**rubygems/-/twitter-text/3.0.0**

CD: https://clearlydefined.io/definitions/gem/rubygems/-/twitter-text/3.0.0
GH: https://github.com/twitter/twitter-text/tree/0220ff43d9d0fc4817f9ff23405303260afd21eb

- All files identified correctly as Apache-2.0; zero NOASSERTION files

**Comment by qtomlinson** [comment]
@bduranc Thanks for filing the issue!  These three cases have been fixed by recent fixes.
https://clearlydefined.io/definitions/gem/rubygems/-/wareki/0.3.0 shows "Declared: BSD-2-Clause"
https://clearlydefined.io/definitions/gem/rubygems/-/uk_account_validator_auctionet/0.0.9 shows "Declared: BSD-2-Clause"
https://clearlydefined.io/definitions/gem/rubygems/-/twitter-text/3.0.0 shows "Declared: Apache-2.0"
Please verify.

**Comment by bduranc** [comment]
This looks to be resolved now. Thanks Qing and team!
