### ISSUE TITLE
Add a simple contribution experience

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#111]
Users looking to add simple contributions or to contribute a curation for something that has not been harvested need a simple way to input the data they have. Editing on the _curation_ page is a bit more advanced and requires that the component is already harvested.

Here I'm thinking of some simple but well structured form that exposes all the right data bits with some field validation.

**Comment by jonasob** [comment]
I dug up some stuff from my previous work, and can contribute some thoughts. This is the wireframe we came up with for our curation pane in the elog.io project: https://github.com/commonsmachinery/catalog/blob/master/doc/wireframes/export/edit_a_work_metadata_editor.png

I'm not saying it's the best, but it is structured. There are two aspects of this which I think would benefit ClearlyDefined:

 1. For curated data, it would be nice to have some abstract understanding of confidence in the data. It doesn't need to be (and maybe shouldn't be, for legal reasons) a percentage indicator, but if we have 4-5 data sources which all indicate that file X is under Y license, then that should be highlighted -- or perhaps hidden -- because we're already quite sure the data is accurate. Instead, the data which is missing, or where there are discrepancies between the data sources, could be highlighted, as those would need manual intervention and work. Simplify by hiding data and showing only that which is most relevant for the curation work.
 2. Not all curation need to happen through the same interface. It should be possible to break out the curation bits, especially where there are discrepancies in the data. Could even do some gamification/crowdsourcing of contributions :-) You have five minutes to spend on helping ClearlyDefined, how can you do that best? One way could be to click a link on the front page, which starts asking you questions. Granted, it's a bit out there and could be mostly marketing rather than collecting reliable data, but some food for thought :-)
     * Look at the source code file to the right, does this file include a copyright notice?
     * In this copyright notice, what would be the name of the copyright holder?

**Comment by fossygirl** [comment]
@jeffmcaffer I think this issue is likely either closable or superseded by the other issues we've opened recently. Can you confirm?

**Comment by jeffmcaffer** [comment]
yup. we have completely revisited the contribution experience.

Having said that, @jonasob second suggestion around gamification and making it really easy to get partial results would be really interesting to preserve somewhere. I like the idea of asking super simple, focused questions that build consensus.

That will be something we do in the future but don't want to forget about it.

I'll close this issue. @fossygirl if you can think of a good place for that design idea in a UI design doc or some such, please do include.
