### ISSUE TITLE
Share URL and lists of components for contribution workflow

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#117]
We are building a workflow for contribution that allows a user to drag and drop components onto a box in ClearlyDefined and that generates a list of components that the user can share with others. 

We have a few potential solutions, but the first try is a button on the page that lets the user "Share this list" and generate json.  @iamwillbar mentioned having an endpoint in this scenario which forces the browser to do the app/download dialogue.

Also came up to think about:
- @jeffmcaffer mentioned we need to make sure File Explorer to drag and drop works to enable this workflow. 
- We are not currently saving sort order for lists, we want to enable that in this list design.

For the record, other considerations from the meeting we might want to explore if needed:
- "the blob solution" where we hash and store by hash, which also gets us the metadata in the blobs and can store sort order for lists.
- compress and encode the components in the URL and experiment with how much we can get into the URL.

@jeffmcaffer @iamwillbar please edit or update if needed.

**Comment by iamwillbar** [comment]
The file format could be JSON or YAML (we should prefer YAML if we think people will open these up and look at and/or hand modify them). The file would include an array property containing the list of components, in the absence of sorting this array should be in the same order as what's shown on the page and this should be honored when importing the file in #41.

In the future, when the UI supports sorting or other UX affordances these should also be stored in the file so that #41 can replicate the same UI when importing the file.

**Comment by jeffmcaffer** [comment]
This work is largely covered by other issues (some of which have been completed). Closing this one to reduce confusion.
