### ISSUE TITLE
cache the clearlydefined badges so as to not abuse shields.io

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#138]
Do this in the website app with a simple memory cache

**Comment by rspier** [comment]
This is an actual, not theoretical problem.  @jeffmcaffer reports that users are seeing broken images, likely due to rate limiting.

**Comment by gauntface** [comment]
Yeah - cloudflare is returning 429 response (too many requests)

**Comment by gauntface** [comment]
We can add a cache control header to the badges on api.clearlydefined.io/badges/* but I don't believe that's the actual issue here. 

Cloudflare is actively rate limiting the value.

<img width="483" alt="screen shot 2018-07-16 at 11 54 40 am" src="https://user-images.githubusercontent.com/139760/42777507-2722aff4-88ef-11e8-865e-24bdb0ea9c43.png">

The best approach would be to add a rule to cloudflare to alter this rate limit (for api.cloudflare.com/* OR api.cloudflare.com/badges/*)

Worth noting that once the badges hit the rate limit, it starts to rate limit the /definitions  calls as well (before hitting the rate limit they didn't seem to contribute to the rate limit)
