### ISSUE TITLE
List can hold entries for which ClearlyDefined does not have data

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#163]
The components list should be able to hold entries for which ClearlyDefined does not have data. This helps users understand where more investigation is needed before using a component.

**Comment by fossygirl** [comment]
@jeffmcaffer Did you get a chance to review this, and can we potentially close this issue?

**Comment by jeffmcaffer** [comment]
Not yet but it is assigned to @Teju-Manchenella  so perhaps he has

**Comment by Teju-Manchenella** [comment]
Yes this is working properly. If a component does not have a specific field (ex. no source location) a place holder value is displayed. Along with that when you drop a package-lock.json file, all the components show up even though most of them have no data in ClearlyDefined (of course with a score 0 since there was no definition). This similar functionality should be seen when we expand into allowing users to view components that have not been crawled by ClearlyDefined, like dragging and dropping package URLs.

**Comment by fossygirl** [comment]
@Teju-Manchenella Then to confirm can we close this issue?

**Comment by Teju-Manchenella** [comment]
Yes we can close this issue
