### ISSUE TITLE
Expanded details display

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#165]
Extra details displayed to users should be:

- Release date
- Source component (if applicable)
- Declared license
- Facet information
- Discovered licenses
- Discovered copyrights
- Tools used to discover the above information
- Statistics about the definition (e.g., number of files, count of files missing licenses, copyrights, …)

**Comment by jeffmcaffer** [comment]
This one is largely done. We need to vet the current data that is shown and make sure it it all makes sense. As the other stories progress, (e.g., rich editing widgets) the details of the expanded view will change but not the general form (once this issue is resolved). This issue is to get the general form right.

**Comment by fossygirl** [comment]
@jeffmcaffer @Teju-Manchenella Can we close this one?

**Comment by jeffmcaffer** [comment]
Yup
