### ISSUE TITLE
Add Gist support for saving of lists

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#168]
We should add Gist support to our save functionality for lists: users should be able to have Gists as a mechanism for storing exported lists and they should be able to drop a Gist URL into the definition list and have the content of the Gist read and the corresponding definitions loaded.

**Comment by caabernathy** [comment]
Just posting my prelim investigations. The underlying component handling Drag and Drop (react-dropzone) doesn't currently handle dragging in URLs. Different from dragging in files, the underlying code rejects the process because the "file name" is `undefined`. It's undefined because the dropzone component is actually an `<input type="file" />` under the hood.

There may be some additional hoops needed to make this work but it isn't obvious to me how this can be done. 

Perhaps, the input's `value` attribute or other element can be extracted to get at the URL and then fetch that content when the default path fails.

Maybe there's a different react component that can handle dragging different type of input other than files. I did a search and haven't found anything thus far.

**Comment by storrisi** [comment]
Given that now that DnD behaviour is implemented, we can work on this.
We can use the Gist APIs to save on a newly Gist file, or retrieve the contents from a dropped Gist URL.

I assume that the content of the file should be the same of the json export.
@fossygirl is that right?
