### ISSUE TITLE
Multiselect for components

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#169]
The contribution UI should allow users to group and multiselect sets of components and contribute changes together as once. They should be able to review the list of changed definitions in the contribution and provide a summary descriptions for that contribution. Users should also get an option for "select all" or "unselect all."

**Comment by jeffmcaffer** [comment]
In the end this is most useful for 
* bulk edit
* saving or contributing a subset of the current list contents.

**Comment by fossygirl** [comment]
@jeffmcaffer I believe this is all implemented and done. Can we close?

**Comment by jeffmcaffer** [comment]
Don't think this even got started. Can you check the UI and see if you can multi-select something?

**Comment by storrisi** [comment]
Multiselection is not yet implemented, but actually is already possible to contribute multiple components at time.
It needs to be discussed again and see if some implementation is needed.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @fossygirl what's your view on this? can this be closed? or are there missing features? (If so we can always open a new issue to track what's left).

**Comment by fossygirl** [comment]
@AlexWebYourmind We'd still like to be able to multi-select components and as far as I know this isn't even started. Curators should be able to select multiple components and make bulk edits, which they can't currently do.

**Comment by storrisi** [comment]
Thanks @fossygirl , we should consider to let the user to edit all the fields for all the selected components?
- License
- Source
- Release Date

Other fields, like Facets, are only editable from the Full Detail View, should these fields be changeable as well?

**Comment by storrisi** [comment]
@fossygirl any updates on this?

**Comment by jeffmcaffer** [comment]
Realistically only the license can be bulk edited on a component. Release date may be relevant if there is a whole family of components released on the same day.  Source location similarly, is only relevant for bulk edit in monorepo-like scenarios where multiple components all coming out of the same commit.

There are also bulk scenarios on the file list.

I do wonder if we could flip this around and do a "format painter" style approach. Rather than picking a bunch of components and applying a license, pick a license and "paint" many components.  I don't have a sense of scale here. How many entries would be "bulk edited".

Whatever we do should be the simplest thing that curators would find useful. Should engage the user in this conversation.

**Comment by storrisi** [comment]
Thanks for your feedback @jeffmcaffer , a user contribution would be very helpful here

**Comment by storrisi** [comment]
@fossygirl @jeffmcaffer we've made a quick implementation on https://github.com/clearlydefined/website/pull/508 , which could be tested on https://deploy-preview-508--clearlydefined.netlify.com/

Would be great to get some feedback on the UI. (FWI: The button or dropdowns don't do anything)
This is to know if we're going to for this is or the "copy-paint" UI
