### ISSUE TITLE
File list view

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#191]
The full details (and other) views should show the list of files that are part of the given definition.  All the per-file information such as the following should be shown

* The path of the file
* The list of facets in which the file appears
* The list of licenses discovered in the file
* The list of copyright statements found in the file

The list should allow relatively easy/natural navigation as it may have many entries. The current thinking is a tree-table style where the left column is a directory tree and the subsequent columns are the above data per file.

That the file list allows sorting and filtering much like the component list is super useful and coherent. Seeing the list of files like I would in a normal operating system file tree view (with expand and collapse) makes me feel at home.  (Note: TBD how the tree view changes in the face of sorting. Filtering could just make it more sparse but sorting changes the structure)

**Comment by fossygirl** [comment]
We have some mockups for the evolution of this list view. 

The first is a read-only view:

![read only tree table view copy with hover](https://user-images.githubusercontent.com/17101092/42352413-37f24336-806f-11e8-9d0a-fb8e52626000.png)

Second phase is a read/write view. Facets should always be a dropdown since there are only 6 and those won't change. Licenses will be expressions, so when we get to this phase we will need a [license](https://github.com/clearlydefined/website/issues/178) and [facet picker](https://github.com/clearlydefined/website/issues/202) as per their respective issues. 

![read_write tree table view](https://user-images.githubusercontent.com/17101092/42352419-3ffd690c-806f-11e8-85fc-fe6608fd277c.png)

Third phase is a filtering option to let users filter on facets or licenses:

![filter on columns](https://user-images.githubusercontent.com/17101092/42352440-5db18938-806f-11e8-8972-f7312217cf07.png)

**Comment by storrisi** [comment]
I've built a sample on stackblitz to test if react-table could do the trick.
The first implementations had some problems, due to the way that react-table groups data in a pivot column.
The problems occur when some folded data has some children different from branch to branch.
react-table assumes that every branch should have the same number of children, so if one them doesn't, it renders an undefined.

I've spent some hours to find how I could overcome this behaviour, and the way I have found seems to fix the problem.

I've started from the HOC TreeTable component that react-table team released, and I've built a customized copy in my project.

Next, I've analyzed the structure of the object passed to the Renderer, and written a function that removes any undefined unnecessary object, 
re-structuring the proper tree-object that should be rendered.

Here you can find a sample of what I've implemented:
https://stackblitz.com/edit/react-ihqxyx

Some other problems need to be solved to accomplish the task.

The idea is, like in this context, to use react-table as a kick-start, and customise a couple of methods to reach our goals.

What I'd like to try to do now, is to build the function that returns the proper object, outside the HOC custom component, so we'll be independent
of any changes to the main library. The same goes for other custom methods.

Before of that, I'd love to have a feedback from you to know if you think this could be the right way to proceed.

**Comment by storrisi** [comment]
I've got a new update for the File List Component.
Here's an updated sample of the requested behaviour, mainly solving Phase 1 (read-only):
https://react-uji3fp.stackblitz.io/

On top of that, there are some behaviours still to  be fixed:
- root data: with react-table, it's not pretty simple to use mixed-types on Pivoted columns, so it accepts by default a folder structure, even for elements at root level.
For now, this has been solved putting those data into a "/" folder, but I am trying again to let those elements render like simple rows. Probably this can be fixed with some CSS workarounds and controlled functionality
- Tooltip on Copyrights: I noticed that some lists of Copyrights are quite large, and a tooltip couldn't be enough to show them all. You can check this by mouse hovering  the ThirdPartyNotices.txt Copyrights column under the "/" folder.

Next step is to move forward on phase 2: editing.
The Github issue mentions Facets Picker and License picker that has yet to be developed. When are the 2 pickers going to be ready? 

In the meantime, how should I proceed with the Licenses edit functionality implementation? (For what's concerning Facets, I can use a static list, given there's only 6 of them)

Thank you!

**Comment by jeffmcaffer** [comment]
code merged. Thanks @storrisi

**Comment by jeffmcaffer** [comment]
addressed by #248
