### ISSUE TITLE
Allow full detail pop-up

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#194]
A user of the definition list should be able to call up the full details of a component without losing all context.  For example, the details might come up in modal dialog or pop-over that can be dismissed. That keeps them on their current page (does not mess with browser history) and feels more integrated.

**Comment by tesmart** [comment]
Just a quick question since I've been out of the loop: I'm thinking about tacking this. We're talking about the component in the screenshot, correct? I was thinking to add a button for "More details".
<img width="1204" alt="screen shot 2018-07-20 at 9 34 04 am" src="https://user-images.githubusercontent.com/35608706/43014649-bc5eb0d0-8c01-11e8-8755-9876bff2571d.png">

**Comment by jeffmcaffer** [comment]
Hey @the smart, check out jm/detailsPage branch for a hack o stat at this.  It's just too start a discussion.  It's hooked into the inspect (magnifying) button. There are a few ideas around for what this should look like.  There's also a fair bit of work in this so would be good to position it up a bit.  For example the will be a facet editor as part of it,  the file list is already under way as a separate component. Check it out and see what you'd like to do.

**Comment by tesmart** [comment]
Good to know Jeff, thanks!

**Comment by jeffmcaffer** [comment]
closing this in favor of #231 which captures the overall scenario and work better.
