### ISSUE TITLE
Link in PR to changed definition going to the wrong place

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#249]
Steps to reproduce:

1. Make a change to a definition on dev.clearlydefined.io.
2. Click contribute, save change, get message your PR was submitted, click on link in message.
3. You're taken to a PR like this one: https://github.com/clearlydefined/curated-data-dev/pull/183
4. The [link in the PR](https://github.com/clearlydefined/curated-data-dev/pull/183#issuecomment-413674099) goes to https://clearlydefined.io/curations/183, which is just the main page of the website.

**Comment by fossygirl** [comment]
The curated-data-dev links are also linking to clearlydefined.io. I don't know if that's intended behavior or not.

**Comment by fossygirl** [comment]
@jeffmcaffer I think we likely need to prioritize this too for the curators so they're able to review each other's work properly.

**Comment by AlexWebYourmind** [comment]
Hi @fossygirl @jeffmcaffer Myself and @storrisi checked into this and it appears that this issue would need to be opened on the CD Service repository.

The reason being that there's no such route as /curations/<id> on the client side, and apparently neither on the service side. Therefore the catch-all route returns the homepage (should wet thing about a 404 page soon or later?).

In order to understand what's the correct way to go, we might need to know the answer to the following questions:

- Is '/curations/id' a Client or a Backend Route? 
- What should be shown on the /curations/id routes? Or is just the link in the PR to be wrong and should point to something else?
