### ISSUE TITLE
"Share URL" button not producing a useful URL

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#251]
Steps to replicate:

1. Search for a component on the Browse page
2. Click "Share URL" button, get message link was copied to clipboard.
3. Paste URL from clipboard into new browser window. In this case I got [this ](https://clearlydefined.io/definitions/eJxNzkEOgyAQBdC7zNoFiIJh2Ws0XSAMLQkyBtDEGO9ebbvocl7+z58dfIgVM+j9aKBQrrcNdFpibMASZReSqVhA33eo24yg4RkqNDBnWoO7ihe8lvG0ZCYss7FXaiJyEX/4f2dcQwmUTmPKS9EPIxOsVVIIz+2Aw8g7a5lwSnHfoepk+5n7fnU8jjcgfjl1)URL
4. URL takes you to a blank ClearlyDefined page

**Comment by AlexWebYourmind** [comment]
@fossygirl This particular issue happens due to the new details page deeplinking implemented as part of #231. 

The Share URL path and the Full Details path are colliding.

The simplest way to address this would be to modify the path for the Full Details page from /definitions/<Full path of the definition> to /definitions/details/<Full Path of The Definition)

@fossygirl  @jeffmcaffer Do you agree with the above? If so, @storrisi please make sure to include a resolution to this particular issue when you have the chance.

**Comment by jeffmcaffer** [comment]
I'm not clear on which URLs are colliding. Can you paste in here examples?

**Comment by jeffmcaffer** [comment]
Ah, thanks for the detail. That helps. The Share URL is largely opaque so frankly it could be any route. Users are unlikely to try and interpret the URL in some way. It's great that it has `/definitions` in it (help users remember what it is) but even that is not a major pivot point. 

The other URL however deep links to a specific definition. Users will IMHO very much want to understand these URLs and they should be as simple as possible. The current `definitions/type/provider/...` form is about as simple and specific as it gets. That one has higher priority. 

If you want to have a special type (e.g., _share or some such) that allows easier routing, that might work.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer Ok, we will focus in changing the Share URL then. ideally we change ti to `/share/<HASH>`.

we'll include it in today's iteration on #231 PR.
