### ISSUE TITLE
Cannot link to definition

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/website#318]
There does not seem to be a way to provide a link to a given definition. It would be handy to have such a thing

**Comment by storrisi** [comment]
@jeffmcaffer this has been removed in [this commit](https://github.com/clearlydefined/website/commit/cc821dcc3571c75b46df814b52e2ba4a25bda9ae) from yourself

**Comment by pombredanne** [comment]
@storrisi FWIW I would prefer the browser URL bar to be a linkable URL rather than having to click on a button: this is the regular web way.

**Comment by jeffmcaffer** [comment]
There may be some confusion here as to the problem. Mechanically deep linking works. For example https://clearlydefined.io/definitions/npm/npmjs/-/async/2.6.0. Philippe, it seems you are saying there is no easy way to get that link. Fair enough. For some reason I removed the "get a link" button and the associated PR here adds it back. As for the browser url bar, that is just .../definitions as it points to a list, not a specific item. We can't use that.

The inspect button opens a pop up (modal) with full details rather than navigating to a new page/tab. That could be changed to be just a link that takes you to a new page/tab. Then users can either click it to navigate or right click and copy url.

Having said that, what we have observed so far is that users like that they have a list, they can drill into an entry and pop right back to the list without disrupting their basic view (no "back" or having to switch tabs, ...)

So summary, the copy URL is more or less like what you see in GitHUb for getting a repo clone url. Suggest we stick with that for now and see the various feedback.
