### ISSUE TITLE
fill in filter bar when navigating back

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/website#35]
In the /inspect page, if you select a component then navigate away (say the curate page) and then come back, the filter bar is not filled in but the data for component you were inspecting is still there/re-populated.

We should use the `selected` prop on the `Typeahead` component in the `FilterBar` to show the current value to the user.

note that this may be relevant for other pages as well.

**Comment by mynameistechno** [comment]
I'm new to react, so will try to tackle this one.

**Comment by mynameistechno** [comment]
Hey @jeffmcaffer just to make sure I understand the problem here. The Component search bar is currently cleared after you select from the suggestions. Are you implying the Search bar shouldn't be cleared after a selection? Seems like we should fix that first if so, and then make sure that the value stays there if you navigate away and come back.

**Comment by jeffmcaffer** [comment]
This is on the _Inspect_ page (recently renamed from _Component_. I updated the initial comment just now). there you are looking at one thing and the selection should" stay while you are looking at it. If you go away and come back, that selection was disappearing.  At least, that is what was happening when this issue was created.
