### ISSUE TITLE
choosing 1 suggestion applies all for that version

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#458]
![2019-02-06 10 53 33](https://user-images.githubusercontent.com/5168796/52365982-8963e200-29fd-11e9-9753-7ab6ad094703.gif)

Click the license suggestion and the date suggestion gets applied.
They should be applied independently

@storrisi fyi

**Comment by storrisi** [comment]
Looks like the Preview API returns some default values once a suggestion is applied on a specific field.

When selecting the license value, and calling the API https://dev-api.clearlydefined.io/definitions/nuget/nuget/-/Newtonsoft.Json/10.0.2?preview=true , with this request:
`{"licensed":{"declared":"MIT"}}`
this is the response returned from the server:
`{"described":{"sourceLocation":{"type":"git","provider":"github","namespace":"JamesNK","name":"Newtonsoft.Json","revision":"5a6ec030a9a88048f945d187a907ae3bab81af66","url":"https://github.com/JamesNK/Newtonsoft.Json/tree/5a6ec030a9a88048f945d187a907ae3bab81af66"},"releaseDate":"2017-04-02","tools":["clearlydefined/1.2.0","curation/supplied"],"toolScore":{"total":100,"date":30,"source":70},"score":{"total":100,"date":30,"source":70}},"licensed":{"declared":"MIT","toolScore":{"total":15,"declared":0,"discovered":0,"consistency":0,"spdx":0,"texts":15},"facets":{"core":{"attribution":{"unknown":20},"discovered":{"unknown":19,"expressions":["MIT"]},"files":20}},"score":{"total":75,"declared":30,"discovered":0,"consistency":15,"spdx":15,"texts":15}},"files":[{"path":"LICENSE.md","token":"b98a397897ff55f76cddc380041507a95a896b2946e0188703bf0496793d6516","license":"MIT","natures":["license"]},{"path":"Newtonsoft.Json.nuspec"},{"path":"lib/net20/Newtonsoft.Json.dll"},{"path":"lib/net20/Newtonsoft.Json.xml"},{"path":"lib/net35/Newtonsoft.Json.dll"},{"path":"lib/net35/Newtonsoft.Json.xml"},{"path":"lib/net40/Newtonsoft.Json.dll"},{"path":"lib/net40/Newtonsoft.Json.xml"},{"path":"lib/net45/Newtonsoft.Json.dll"},{"path":"lib/net45/Newtonsoft.Json.xml"},{"path":"lib/netstandard1.0/Newtonsoft.Json.dll"},{"path":"lib/netstandard1.0/Newtonsoft.Json.xml"},{"path":"lib/netstandard1.3/Newtonsoft.Json.dll"},{"path":"lib/netstandard1.3/Newtonsoft.Json.xml"},{"path":"lib/portable-net40+sl5+win8+wpa81+wp8/Newtonsoft.Json.dll"},{"path":"lib/portable-net40+sl5+win8+wpa81+wp8/Newtonsoft.Json.xml"},{"path":"lib/portable-net45+win8+wpa81+wp8/Newtonsoft.Json.dll"},{"path":"lib/portable-net45+win8+wpa81+wp8/Newtonsoft.Json.xml"},{"path":"tools/install.ps1"},{"path":".signature.p7s"}],"coordinates":{"type":"nuget","provider":"nuget","name":"Newtonsoft.Json","revision":"10.0.2"},"_meta":{"schemaVersion":"1.4.0","updated":"2019-02-06T21:06:35.198Z"}}`

As you can see, the sourceLocation field is returned with a value.

The same happens when choosing a Source URL , but in this case the definition is returned with a NOASSERTION license.

Request:
`{"described":{"sourceLocation":{"type":"git","provider":"github","namespace":"JamesNK","name":"Newtonsoft.Json","url":"https://github.com/JamesNK/Newtonsoft.Json/tree/d50b912e9948472e122cfaf24ffeebbf77032806","revision":"d50b912e9948472e122cfaf24ffeebbf77032806"}}}`

Response:
`{"described":{"sourceLocation":{"type":"git","provider":"github","namespace":"JamesNK","name":"Newtonsoft.Json","revision":"d50b912e9948472e122cfaf24ffeebbf77032806","url":"https://github.com/JamesNK/Newtonsoft.Json/tree/d50b912e9948472e122cfaf24ffeebbf77032806"},"releaseDate":"2017-04-02","tools":["clearlydefined/1.2.0","curation/supplied"],"toolScore":{"total":100,"date":30,"source":70},"score":{"total":100,"date":30,"source":70}},"licensed":{"declared":"NOASSERTION","toolScore":{"total":15,"declared":0,"discovered":0,"consistency":0,"spdx":0,"texts":15},"facets":{"core":{"attribution":{"unknown":20},"discovered":{"unknown":19,"expressions":["MIT"]},"files":20}},"score":{"total":15,"declared":0,"discovered":0,"consistency":0,"spdx":0,"texts":15}},"files":[{"path":"LICENSE.md","token":"b98a397897ff55f76cddc380041507a95a896b2946e0188703bf0496793d6516","license":"MIT","natures":["license"]},{"path":"Newtonsoft.Json.nuspec"},{"path":"lib/net20/Newtonsoft.Json.dll"},{"path":"lib/net20/Newtonsoft.Json.xml"},{"path":"lib/net35/Newtonsoft.Json.dll"},{"path":"lib/net35/Newtonsoft.Json.xml"},{"path":"lib/net40/Newtonsoft.Json.dll"},{"path":"lib/net40/Newtonsoft.Json.xml"},{"path":"lib/net45/Newtonsoft.Json.dll"},{"path":"lib/net45/Newtonsoft.Json.xml"},{"path":"lib/netstandard1.0/Newtonsoft.Json.dll"},{"path":"lib/netstandard1.0/Newtonsoft.Json.xml"},{"path":"lib/netstandard1.3/Newtonsoft.Json.dll"},{"path":"lib/netstandard1.3/Newtonsoft.Json.xml"},{"path":"lib/portable-net40+sl5+win8+wpa81+wp8/Newtonsoft.Json.dll"},{"path":"lib/portable-net40+sl5+win8+wpa81+wp8/Newtonsoft.Json.xml"},{"path":"lib/portable-net45+win8+wpa81+wp8/Newtonsoft.Json.dll"},{"path":"lib/portable-net45+win8+wpa81+wp8/Newtonsoft.Json.xml"},{"path":"tools/install.ps1"},{"path":".signature.p7s"}],"coordinates":{"type":"nuget","provider":"nuget","name":"Newtonsoft.Json","revision":"10.0.2"},"_meta":{"schemaVersion":"1.4.0","updated":"2019-02-06T21:13:59.686Z"}}`

**Comment by dabutvin** [comment]
I see. I can debug this further in the service

**Comment by dabutvin** [comment]
I think that I just screwed this one up by modifying the definition to set up this scenario..I'll double check, but we may be good to go
