### ISSUE TITLE
FileList collapses when fields are edited

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#469]
The tree should stay in it's current state when a change is made. Right now, when a change is made it collapses and has to be reopened each time something changes

![2019-02-14 12 50 32](https://user-images.githubusercontent.com/5168796/52816925-2d313b80-3057-11e9-9857-d5bb2bcadc1f.gif)

**Comment by dabutvin** [comment]
@storrisi is this something you can track down?

**Comment by fossygirl** [comment]
Might be related to https://github.com/clearlydefined/website/issues/270#issue-354895564?

**Comment by storrisi** [comment]
This is much more likely related to #343 , i will check out to see if react-table has now some updates to fix this problem.

**Comment by storrisi** [comment]
This looks like to be a very complicated bug to solve.

If we remove the auto-collapse, react-table adds some undefined folders out of nowhere, that we are not able to remove from the outside.

I've searched from similar bugs but it looks like this should be solved with the version 7, which is currently in an alpha stage.

**Comment by storrisi** [comment]
I've made some tests trying to fully control the table, instead of give the control to react-table itself, in order to keep the filelist open while updating, using the `expanded` prop and the `onExpandedChange` method from the official documentation.
But at that point the weird thing is that the `pivotBy` prop creates a fixed structure that apparently is not possible to mutate.

For example, given a folder structure like: 

```
[
{'name': 'LICENSE.md', folder_0: '/'},
{'name': 'test.js', folder_0: '/'},
{'name': 'script.js', folder_0: 'tools'},
{'name': 'README.md', folder_0: 'lib', folder_1:'test'},
]
```
it considers that all the elements should have always the maximum value of folders (2, in this case).

Given that, it creates as many `undefined` folders in order to have all the files nested in the same way.

Real example:
<img width="998" alt="schermata 2019-02-20 alle 16 37 40" src="https://user-images.githubusercontent.com/7654979/53103408-e303fa80-352d-11e9-8b1f-42690c0427a7.png">

**Comment by storrisi** [comment]
As per discord discussion, we will try to find an alternative solution to `react-table`.

**Comment by storrisi** [comment]
We've found a good solution in ant-design table.
Since we are already using ant-design for some elements in the UI, using the built-in Table component looks worthwhile.

It has also some useful behaviors out of the box that meets perfectly our needs.
I'm currently working on switching from react-table to ant-design and i will provide a PR soon.
