### ISSUE TITLE
File Filter Improvement: Licenses

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/website#511]
It is helpful for curators to be able to filter by discovered licenses.  The current free-form text box produces some noise because of similarity of some license SPDX identifiers (e.g. LGPL/GPL). 

While helpful to be able to filter for all "GPL" and/or "LGPL" the current filtering makes it difficult to quickly search for a particular discovered license.  Perhaps only search for things beginning with the filter string by default and include a wild-card capability (if, for example, the user wants to search for all GPL AND LGPL).  Another option could be to support Boolean searching limited to the list of discovered/declared licenses in the component.

![image](https://user-images.githubusercontent.com/36014796/53430498-a1a39d00-39bc-11e9-96f1-a1c99ddd7967.png)

**Comment by jeffmcaffer** [comment]
Makes sense and is likely a trivial change.

**Comment by storrisi** [comment]
I think that the proposal of a Boolean search, rather than a free text, could be helpful in this case.
We could also allow the user to select multiple values in order to select different kind of discovered copyrights.
Perhaps this kind of filter could save time to the user that is searching for some specific values.
The same could happen for the License filter as well.

@jeffmcaffer what do you think?

**Comment by storrisi** [comment]
@jeffmcaffer do you have any additional comment on this? I would be happy to work on it and bring this change in place.
