### ISSUE TITLE
Need validation on facet user entries

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#562]
I think it's possible right now to enter anything into a facet glob expression, we need to do validation on the users' entries there so they can't enter bogus stuff.

**Comment by gianpaj** [comment]
We could possibly use this package or similar ones:
https://github.com/micromatch/is-glob

**Comment by storrisi** [comment]
We could track this thing while working on a more general "GlobPicker" as discussed with @jeffmcaffer and @dabutvin on Discord, and mentioned in #478 .

As @jeffmcaffer said, who knows how a glob picker works could type in those correctly. Everyone else needs some kind of help, and we should be able to guide in some way the user on applying facets on folders, files, or file extensions.

I think that this implementation should be a standalone component like the LicensePicker, since i don't know any other component that currently does the same thing.

Thoughts?

**Comment by storrisi** [comment]
@gianpaj and i have discussed a little bit around this and #478 topic.

As suggested by @jeffmcaffer , we should proceed incrementally, and we think that starting from this implementation, rather than implement the FileList facets editing behavior, could be beneficial for the User.

Implementing a smart GlobPicker, something guided like the LicensePicker, could help the user to create expressions in an interactive and easy way.
Searching around the web we've found [this solution](https://globster.xyz/) that we could take as example.

What we are thinking is to implement a Typeahead field, that shows incrementally to the user the options that he has while creating a new glob expression.

An example of usage could be:
- if the field is empty, you can choose between "Everything recursively" or a specific folder (a list taken from the file list)
<img width="421" alt="Schermata 2019-03-12 alle 16 18 27" src="https://user-images.githubusercontent.com/7654979/54211977-7fdd0680-44e2-11e9-9742-6e47a3ef7eb3.png">

- if you selected "Everything recursively" , then you can choose between 'Every file with the same extension' or 'Exclude some files'

<img width="423" alt="Schermata 2019-03-12 alle 16 21 51" src="https://user-images.githubusercontent.com/7654979/54212269-f7129a80-44e2-11e9-9599-752360768bce.png">

- then you can choose from a list of file extensions, picked from all the available in the file list
<img width="425" alt="Schermata 2019-03-12 alle 16 23 11" src="https://user-images.githubusercontent.com/7654979/54214089-e1eb3b00-44e5-11e9-9b06-bdbb0c646b59.png">


Like the License Picker, while the using is selecting all the values, a Glob Expression is shown somewhere and validated.
We can even show a live result to the user, like the [linked example](https://globster.xyz/), where the user is able to see the effects of the expression.

Thoughts?

**Comment by fossygirl** [comment]
@dabutvin Can you weigh in on this? It all seems fine to me.

**Comment by dabutvin** [comment]
I'm afraid a wizard like experience here is going to cause more problems than it solves.

I think we should leave the glob expression section of the UI as-is so we can surface the way the data is persisted and enable the advanced user scenario to quickly write globs as they see fit.

To focus on some simple scenarios for incremental improvements, I think we need to look at the filetree and let the most basic interactions happen there. 

 - Adding an entire folder to a facet
 - Adding a single file to a facet


Here are the steps I think this would require

1. Remove 'Core' from showing up in the UI. This is really just the absence of a facet and I think it will confuse things
2. Make the facets area editable in the file tree (the same way copyrights) so there can be multiple, but restricted to the 5 pre-defined facets
3. Make the folder level display facets as the set of all the facets contained within them

 - if a user sets a facet on a folder add `/path/to/folder/**` as a glob in that facet
 - if a user sets a facet on a file add `/path/to/file` as a glob in that facet

**Comment by storrisi** [comment]
Thanks @dabutvin i got your point.

If all of you agree with this solution, i'm happy to implement it.
Can you confirm that we should proceed following this approach?

For what is related to this specific topic, then i suggest to coming back to the @gianpaj solution, using https://github.com/micromatch/is-glob to validate the inserted glob-expression.

Thoughts?

**Comment by storrisi** [comment]
@dabutvin @fossygirl @jeffmcaffer do you have any updates on this?

There are different approaches and proposal that we can deal with.
I just want to be sure that we are all on the same page.
