### ISSUE TITLE
Add sort after Browse page "Fix something" selection

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#593]
Once a user has made a "Fix something" selection from the dropdown we should then sort to display lowest-scored components first.

**Comment by storrisi** [comment]
We can do it forcing the call to the API passing the `effectiveScore` param with `sort=asc` together with the `curate` filter.

@dabutvin could you confirm this workflow?

This should automatically activate the Sort By Lowest Score option, otherwise doesn't know what kind of sorting is enabled.

@fossygirl  do you agree?

**Comment by fossygirl** [comment]
@storrisi Yes, agreed.
