### ISSUE TITLE
Workflow: Multiselect - In the Contribution dialog show the list of components with changes/being contributed

### ISSUE THREAD

**Issue by gianpaj** [clearlydefined/website#617]
From the [comment](https://github.com/clearlydefined/website/pull/508#issuecomment-474026332) in #508

**Comment by dabutvin** [comment]
this is an awesome idea - even beyond multiselect.

We should surface a summary of the changes to the user

**Comment by bduranc** [comment]
From an end-users point of view, I will +1 this.

Right now, using the work list is difficult because when you click Contribute, everything is submitted under one PR. This is OK for one or two components that have minor curation (say only top-level license data), but becomes really cluttered to file the single PR when doing > 2 components with more specific curation work, say being done on the file level.

I think having this multi-select ability would be a huge improvement to the existing contribution workflow if we could select only items we want to have in the contribution PR. This way curators could "stagger" their PRs out a bit to coincide with specific components and cases.
