### ISSUE TITLE
Sort by highest score doesn't produce an ordered descending list

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#637]
This list is sorted by Highest Score. You'll see things with 0's appear before things with 40's and 50's.

![Screen Shot 2019-03-28 at 4 07 52 PM (2)](https://user-images.githubusercontent.com/17101092/55198595-d5b4de00-5173-11e9-86d2-65cfe2c512a6.png)

**Comment by storrisi** [comment]
I'm receiving some different results in production using the same filter:

![Schermata 2019-03-29 alle 09 38 32](https://user-images.githubusercontent.com/7654979/55219967-73f18400-5206-11e9-9a60-57f63ab13bb0.png)

BTW this is much more a service problem, since the UI doesn't apply any kind of sorting in this case.
Data are shown as the service returns.

I think we should move this issue in the service repo.

**Comment by storrisi** [comment]
I've opened https://github.com/clearlydefined/service/issues/464 which address this problem.

**Comment by fossygirl** [comment]
Sure, closing.
