### ISSUE TITLE
Give user feedback when things are queued for harvesting

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/website#687]
Right now we don't have any messaging for users when they POST to the API something that we don't have and we queue it for harvesting. We should provide a message or some sort of feedback that "we don't have this now, but it's been queued, check back later!"

**Comment by storrisi** [comment]
We have [this implementation](https://github.com/clearlydefined/website/pull/632) under review that actually checks for something that is not already harvested and automatically ask for an update to the service.

Instead of saying "we don't have this now, but it's been queued, check back later!" i would suggest to show a first notification like "some definitions are not already harvested, we'll notice you once the operation will finish", and then show a notification once the service has returned some data.

Thoughts?

**Comment by storrisi** [comment]
@fossygirl @dabutvin do you have any feedback on this?

**Comment by storrisi** [comment]
As discussed in our weekly meeting, i've added in #632 an implementation to show notifications when the harvest process has been started / ended

**Comment by storrisi** [comment]
Since this requirement has been covered in #632 , we can close this one.
