### ISSUE TITLE
Move license suggestions into the spdx picker

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/website#705]
right now the suggestions are next to the license picker as an 'i'

![image](https://user-images.githubusercontent.com/5168796/57472665-e2ccee80-7242-11e9-87a5-09bed2eb28eb.png)

It would be great to add them to the top of the spdx picker when you open it instead.

Similar to how we separate the NONE/NOASSERTION in the filterbar, we can separate and label the suggestions.

```
--------------------------
suggested
-----------
MIT (version 1)
Apache-2.0 (version 2)
all
------------
NONE
NOASSERTION
0BSD
AFL
...   
```

(all and suggested would be lighter font)
suggested and all may need to have different padding to make it clear they are grouped

**Comment by storrisi** [comment]
Even if i agree with the solution, i'd like to notice that doing that we can loose some of the suggestions functionalities, like show where the suggestion comes from and why.
Also, the user wont be able to see the suggestion since he starts typing in the License field.
Thoughts?

**Comment by dabutvin** [comment]
great points. I was mostly looking to free up some of the icons surrounding the license picker
revert + pencil + eyeball + (i) 

it feels like too much.

I think we can ideally show the source of the suggestion in-line with the item
As for losing the suggestion once you start to type, backspacing could bring them back - I think that would work well

**Comment by storrisi** [comment]
Got your point.
Probably we can involve into the discussion someone that actually use the application and can give a feedback from a user point view, like @bduranc for example.

**Comment by bduranc** [comment]
@storrisi @dabutvin :

You've both brought up some very good points. 

I agree about being conscious of excess clutter concentrated around key fields. I guess the question to ask ourselves for the UI is "how much is too much in one area?", i.e. is more than two buttons per field a problem. For myself at least, I feel the simpler we keep it the better.

Overall, the suggestion feature itself looks really cool and I think would be really beneficial to curators.

The biggest concern I have is if there are a large number of license recommendations showing up in the list (say anything >5). If this could happen, then the list could get too long and awkward to fit on the UI.

Also, if I may ask, where are these suggestions sourced from? is it whatever source the package was harvested from? or is there a dependence on a source location (GH at this moment) being populated?

Assuming the recommendations are based on an indexing of past component versions, it is beneficial I think to have this history in general, but an additional benefit is you also get to see a trend of license changes version to version. A good enhancement IMO would be what we are already doing for [some of the Nuget packages](https://github.com/clearlydefined/curated-data/pull/1418) (obtaining data from LICENSE.MD) and checking the history of the license file.

As for the placement of the suggestion feature in the UI, I think it would be nice to see this feature both where it is proposed now, but also inside the modal dialog that results from clicking the "pencil" icon next to the field (since it appears now that is the only way to add an SPDX expression to that field).

<img width="918" alt="2019-05-10_10-37-46" src="https://user-images.githubusercontent.com/31491646/57547807-36f3d380-7314-11e9-9c28-f9f5016291fb.png">

**Comment by storrisi** [comment]
> The biggest concern I have is if there are a large number of license recommendations showing up in the list (say anything >5). If this could happen, then the list could get too long and awkward to fit on the UI.

Well, i don't know if this is really possible. Since suggestions are taken from other version of the same definition, is there the possibility to have the same field with >5 different values during time?
BTW i agree, if the list becomes too long it would be difficult for the user to interact with.

> Also, if I may ask, where are these suggestions sourced from? is it whatever source the package was harvested from? or is there a dependence on a source location (GH at this moment) being populated?

It takes the same information from other version of the same definition that have been curated recently.

>  it is beneficial I think to have this history in general, but an additional benefit is you also get to see a trend of license changes version to version.

If this is really important as it looks, then i would suggest to keep the list as it is already, and maybe improve it with other useful details.

> As for the placement of the suggestion feature in the UI, I think it would be nice to see this feature both where it is proposed now, but also inside the modal dialog that results from clicking the "pencil" icon next to the field 

Yes, we can do it.

> (since it appears now that is the only way to add an SPDX expression to that field).

Not totally true, a change has been recently released, so now you are able to type a valid SPDX definition in the License picker (if you already know the structure) and use it suddenly.

**Comment by storrisi** [comment]
With all these considerations, are we able to take a decision on this topic? I'd be happy to implement the best solution that meets everyone's needs.

**Comment by storrisi** [comment]
@dabutvin @bduranc do you have any other feedback on this topic?

**Comment by bduranc** [comment]
@storrisi: Overall, I really like the proposal. 

I still think it should be in the license picker dialog as this is where the user makes their selection, but the blue "i" button next to the field as originally proposed is a good start. Furthermore, if the "i" button is what we have already done for other recommendation fields, then we should keep it consistent overall.

**Comment by dabutvin** [comment]
I like the suggestion of putting suggestions in the popups 👍 
I still feel like we should remove the blu "i" to reduce the amount of clutter in the UI and instead prepend the suggestions to the top of the list when choosing inline
