### ISSUE TITLE
[Feature request] Implement harvest status indicator

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/website#742]
It is difficult for the average user to know when a component has completely finished being harvested.

What are the ideal combination of indicators to show a component has been harvested 100% (i.e. component crawled, all scanner tools run to complete) without any question?

**1. Is it when we see the definition listed in the Workspace search field?**

<img width="803" alt="2019-06-07_16-56-00" src="https://user-images.githubusercontent.com/31491646/59139279-0caf2900-8947-11e9-9547-ec46996f02e1.png">

_This field is probably not the best indicator as the results in relation to harvest progress seem to vary:_

_For example,_ 

_[https://clearlydefined.io/definitions/git/github/simplesamlphp/simplesamlphp/f5ff7c4643b9b784957f5e1fbf86fc740cd6b78a ](https://clearlydefined.io/definitions/git/github/simplesamlphp/simplesamlphp/f5ff7c4643b9b784957f5e1fbf86fc740cd6b78a) **does** show up in the search field._ 

_However as of 6/7/2019 4:50 PST, not all tools have successfully run (there is some raw data in the "Harvested data" tab that suggests it has identified some license matches, but no other indicator of harvest progress appears visible).__ 

_On the other hand, [https://clearlydefined.io/definitions/git/github/tyrus-project/tyrus/8698c4411aad042a701a1c8ac03ffb436cc79322](https://clearlydefined.io/definitions/git/github/tyrus-project/tyrus/8698c4411aad042a701a1c8ac03ffb436cc79322), **does not** show up in the search field but it looks like all expected tools have completed (6/7/2019 4:50 PST)_

<img width="846" alt="2019-06-07_16-57-24" src="https://user-images.githubusercontent.com/31491646/59139307-29e3f780-8947-11e9-8b73-8fb0a71c8618.png">

**2. Is it when we see all the expected tools have run on that definition?**

<img width="370" alt="2019-06-07_16-33-11" src="https://user-images.githubusercontent.com/31491646/59138492-492c5600-8942-11e9-9ac9-0dd858c502bb.png">

**3. Is it when we see the component's "Dig into Definition" button visible on a Workspace list item?**

<img width="163" alt="2019-06-07_16-34-01" src="https://user-images.githubusercontent.com/31491646/59138518-7416aa00-8942-11e9-8a1e-43cbb5ec321b.png">

None of the above cases offer a perfectly clear picture of the harvest situation for a given component.

I think it may be worthwhile to explore the idea of having a "pending harvest" indicator to show when key steps of a component's harvest have been successfully completed.

In the UI, it could be an indicator similar to what we currently have for "Pending curations".

<img width="402" alt="2019-06-07_16-40-05" src="https://user-images.githubusercontent.com/31491646/59138634-16369200-8943-11e9-9d82-648334515840.png">

Other improvements upon this concept would be having the full progress represented as a percentage (50% complete, 90% complete, etc.) or "yes/no" indicators to show when each scanner tool has successfully run. 

These suggestions would all help improve the harvest progress transparency for a component.

**Comment by storrisi** [comment]
These are all great points @bduranc .
I don't know if we are really able to show a percentage of harvesting, but we can add a "Pending Harvest" for sure.

@geneh @iamwillbar which should be the conditions that we should check to consider a component in that status?

**Comment by geneh** [comment]
There is no notion of all tools since some tools may be temporarily or permanently disabled, new tools may be added and some tools may fail. Once at least one tool had run, a component may be considered as partially or fully harvested.

**Comment by iamwillbar** [comment]
@fossygirl and I were discussing this earlier and think it would be a good topic for the weekly meeting to get broader feedback on the scenarios.

**Comment by bduranc** [comment]
@iamwillbar : I have no objection.

**Comment by ariel11** [comment]
@iamwillbar - I have received "failed contribution" errors when trying to curate the declared license for components that weren't fully harvested.  Would be helpful to know/see if a component is not ready for curations.

**Comment by storrisi** [comment]
We discussed in the 17th June meeting to insert an idea of component “state”: Just harvested, currently running tools, nothing queued.
@geneh do we have a strategy here?

**Comment by geneh** [comment]
As I've stated before, it's impossible to know whether all the tools have run since a tool may be disabled (e.g.fossology), or simply failing (e.g. scancode for huge components).
How about the following states?

If there are no tools: Not harvested
Only clearlydefined tool: Pending harvesting
More than one tool: Partially/fully harvested

I'm not sure if it adds any value though.

**Comment by bduranc** [comment]
@geneh : I think this would be a step in the right direction. 

However, I don't think we want to advertise a component as being "fully" scanned when the full suite of tools available at that point in time have not run on it yet. I suppose no component can be "fully" scanned as new tools could be added and current ones removed. But we should at least know all tools available to us at the time of a component's harvest, even if we may not be able to predict the exact order of execution or their success.

So at minimal:

If there are no tools: Not harvested
Only clearlydefined tool: Pending harvesting
More than one tool: Partially harvested
All tools available at that time: Completely harvested (no failures)

We should probably refine what "more than one" tool would be. 

Would it be just any tool, or a specific tool such as ScanCode? 

Also, how often do we disable tools? And is the objective eventually to see those tools brought back into production again? (for example with "fossology")

I think there would be benefit in at least being able to know if a tool has failed. I'm sure most tools like ScanCode provide a log or standard output where an error code could be obtained from. If the tool falls over because a larger scan, users should be able to know about this, especially those who plan to curate immediately after harvest. (See: https://github.com/clearlydefined/crawler/issues/320)

I know the above assumes a lot, I'm not an expert when it comes to the scan tooling, but I do know that https://github.com/clearlydefined/service/issues/569#issuecomment-505597144 describes a "precedence order" for the tools when it comes to merging or overwriting data. So to me at least, this suggests a requirement to have some degree of information of which scanners have run and which have not.

**Comment by storrisi** [comment]
@geneh @bduranc perhaps we can help the user to understand the situation by matching all the available tools with all the effective ran on a single component.

For example: if the service could return a list of all available tools that could run, with a specific endpoint, then the UI could match which ones have run for a specific component, and tell if the component has been harvested or not, if partially or fully.

Thoughts?

**Comment by bduranc** [comment]
Ah, so we would not be limited to matching tool versions at a specific point in time, but basically matching a definition to the latest available tools. So does this mean we'd run this as a check at a routine frequency?

This could be a good starting point. But would this lead to any actionable outcome? Like could someone re-run the scan with the latest tools if they see there are gaps? 

Either way, the same question can also be asked with my proposal. User may know there was an error or tools not run, but how can they take action (or will the tool try and correct itself, i.e. re-run with the (new) tools)?

**Comment by geneh** [comment]
What if the tool set changes? In this case many components are going to have incorrect status when trying to match all the tools. If a time dimension were added here, i.e. which tools were available at a certain point in time, the implementation would become too complicated.
What if a tool fails because there is not enough memory and it will keep on failing even if attempting to re-harvest? 
Even if not all the tools run, it is possible, for example, for a license to be detected and a component to be curated. 
I guess the question here is when can a component be curated. Is it when clearlydefined tool and either licensee or scancode tool have run? If that's the case, I suggest three states:
- No tools - Not harvested
- One tool - Partially harvested
- Two tools or more - Harvested
As an alternative, we can also add a tooltip near the tools explaining the number of expected tools etc.

**Comment by storrisi** [comment]
@bduranc what do you think about the proposal by @geneh ?

**Comment by iamwillbar** [comment]
Earlier in the year I put forward a proposal to @jeffmcaffer and it's relevant to this discussion so duplicating it here for your consideration:

I think it can be done relatively easy using a cache similar to what we had in GHCrawler. Here’s how I would envisage it working:

When a coordinate is queued for crawling a record is added to a cache with the coordinates and an array that will be used to track the tools that are queued for that root coordinate. Initially this array will contain a single entry for the root containing the message id of the queue record and a flag for that message id saying it’s in progress:
`npm/npmjs/-/redie/0.1.0: [{messageId: “a”, state: “queued”}]` – at this point we have queued the root (a)

When the crawler picks an entry off the queue, it does its work as usual, but when it queues additional things to run, it does two things:
1. Includes context in the queued items which indicates the root coordinates that were requested (so we can update the cache on the root coordinate)
1. Adds additional items to the array attached to the root coordinates
   `npm/npmjs/-/redie/0.1.0: [{messageId: “a”, state: “queued”}, {messageId: “b”, state: “queued”}, {messageId: “c”, “state”: “queued”}]` – the root job is currently running and it has queued (b) and (c), progress tracker would show 0 of 1

At this point the root job might complete, so it updates itself inthe array, this must be done *after* it has queued anything it is going to queue (so that the root doesn't appear complete briefly)
`npm/npmjs/-/redie/0.1.0: [{messageId: “a”, state: “completed”}, {messageId: “b”, state: “queued”}, {messageId: “c”, “state”: “queued”}]` – the root is complete so it is updated in the array, but (b) and (c) are still in progress, progress tracker would show 1 of 3.

This continues to whatever depth, however, everything gets added to the array for the root coordinates that were originally queued.

We can decide whether transitioning from package to source is actually a new root or not. Given that the API to retrieve a definition doesn’t traverse to source it probably make sense to treat source as a new root.

`npm/npmjs/-/redie/0.1.0: [{messageId: “a”, state: “completed”}, {messageId: “b”, state: “completed”}, {messageId: “c”, “state”: “completed”}, {messageId: “d”, “state”: “queued”}]` – at this point (b) and (c) are complete but (c) queued (d), progress tracker would show 3 of 4.

If we wanted to you could easily extend this to track “running” separate from “queued” so you could say 3 are in queue, 2 are running, and 4 are complete and people just need to understand that the totals will change as we discover more that need to be crawled, however, because we always queue new items before marking "completed" if all of the array entries show "completed" then we know we are done.

**Comment by bduranc** [comment]
Sorry for the delay in response. 

> @bduranc what do you think about the proposal by @geneh ?

I think this is pretty close. I like the idea of the tooltip explaining the total number of expected tools queued. I suspect this would be expected tools available at current, and not at the specific time of harvest. I.e. say I harvest a component on August 30th and it finishes that same day. Then if we put in a new tool August 31st, would that new tool would be visible in the tooltip? I am guessing yes.

> Even if not all the tools run, it is possible, for example, for a license to be detected and a component to be curated.

True. But even if one can proceed on a component with a failed tool, they should still be able to know what was expected to run but had failed, even if there is initially no reason detail provided for the failure. If there are no tools run at all (aside from "clearlydefined"), then it becomes even more difficult to proceed.

> I guess the question here is when can a component be curated. Is it when clearlydefined tool and either licensee or scancode tool have run?

That is precisely the question. ScanCode or Licensee in most cases are the minimum scan tools I observe run on a component (either one, the other, or both) aside from "clearlydefined". The "clearlydefined" tool I would probably place in the "partially" (or in [my example](https://github.com/clearlydefined/website/issues/742#issuecomment-513344185), I refer to "pending"; "partially" is reserved for if a tool other than "clearlydefined" has run; though I'm fine with whichever) harvest stages as my understanding this is mainly project metadata.

Also, how often do we disable tools? And is the objective eventually to see those tools brought back into production again? (for example with "fossology")

@iamwillbar's proposal I think is also in the right direction and explains from a more technical perspective how we could accomplish this.

> When the crawler picks an entry off the queue, it does its work as usual, but when it queues additional things to run, it does two things:

Just to confirm, the "additional things to run" would be any tools started by the crawler? ScanCode, licensee, etc? Is "clearlydefined" tool considered part of this array (is it item "a") ?

> If we wanted to you could easily extend this to track “running” separate from “queued” so you could say 3 are in queue, 2 are running, and 4 are complete and people just need to understand that the totals will change as we discover more that need to be crawled, however, because we always queue new items before marking "completed" if all of the array entries show "completed" then we know we are done.

It would be extremely beneficial to see what tools have been queued for a component and what's already running. I think you describe much of the core functionality required. But people should also be made aware if there is one fails.

> npm/npmjs/-/redie/0.1.0: [{messageId: “a”, state: “completed”}, {messageId: “b”, state: “completed”}, {messageId: “c”, “state”: “completed”}, {messageId: “d”, “state”: “queued”}] – at this point (b) and (c) are complete but (c) queued (d), progress tracker would show 3 of 4.

Can you elaborate on what you meant by "(c) queued (d)"? I was under the impression reading this that only the root/parent process (a) can spawn the sub-processes. And if either is the case, since this appears to be _after_ "a" was set to "complete", why does the spawning process "a" (or "c") not return back to "queued"? 

> Adds additional items to the array attached to the root coordinates
npm/npmjs/-/redie/0.1.0: [{messageId: “a”, state: “queued”}, {messageId: “b”, state: “queued”}, {messageId: “c”, “state”: “queued”}] – the root job is currently running and it has queued (b) and (c), progress tracker would show **0 of 1**

Should this not be 0 of **3** ?

So overall, I think if we can at least do something like:

```
**No tools** - Not harvested
**One tool** - Partially harvested (including "clearlydefined" tool?)
**Two tools or more** - Harvested (including "clearlydefined" tool?)
As an alternative, we can also add a tooltip near the tools explaining the number of expected tools etc.
```

That would be a good place to start. Even better, if we can include information on if a failure has occurred, perhaps maybe by incorporating @iamwillbar's proposal but adding a fourth state of "failed" ("completed", "queued", "running", "failed").

**Comment by storrisi** [comment]
@bduranc just to summarize, can we consider to implement this kind of statuses that you mentioned?

```
**No tools** - Not harvested
**One tool** - Partially harvested (including "clearlydefined" tool?)
**Two tools or more** - Harvested (including "clearlydefined" tool?)
As an alternative, we can also add a tooltip near the tools explaining the number of expected tools etc.
```

**Comment by bduranc** [comment]
Sounds good to me. 
Also, where I say "including 'clearlydefined' tool?" I think this should be a "yes". When we count tools, we should also include "clearlydefined" as a measured tool since it does show up in the list.

My understanding is this "clearlydefined" entry in the tools list just represents the metadata that CD itself has been pulled from the source repository (name, version, release date, dependencies if taken direct from NPM, etc.) and no actual scanners. 

Please correct me if this is wrong.

**Comment by storrisi** [comment]
@jeffmcaffer I'm going to answer just to the questions where I'm actually able to contribute:

>what happens when a new tool is added

It won't change the result since the method is just considering the tools that have run on the definition, and not the expected ones.
For example:
- If a definition is currently returning only 1 tool, we are considering it as "Partially Harvested", so the addition of a new expected tool to run won't change the label
- If a definition is considered "Fully Harvested" then it means that 2 or more Tools have already run on itself. The addition of a new expected tool won't affect the label also in this case.

>is the "done" value included in the API? or is this purely a UI affordance?

This is a computed data directly on the UI based on the number of ran tools on each specific definition.
