### ISSUE TITLE
Can't fix Maven Central source URLs in the UI

### ISSUE THREAD

**Issue by waynebeaton** [clearlydefined/website#889]
The UI only supports updating to GitHub source URLs.

It would be handy to be able to update to an arbitrary URL.

**Comment by nellshamrell** [comment]
We discussed this issue at Monday's community meeting.

I'm guessing this was in reference to incorrect Maven Urls (which has since been corrected for all new definitions - I'm working on a script to update all the previous Maven definitions). This was a systematic issue that has been fixed. We don't feel that there is a pressing need to allow someone to manually update these URLs at this time, but we can revisit in the future if needed.
