### ISSUE TITLE
Search filter does not filter type

### ISSUE THREAD

**Issue by capfei** [clearlydefined/website#957]
Tried searching for npm package called "[cli](https://www.npmjs.com/package/cli)", but search suggestions show everything even though filter is set to "NpmJs". Same result if I change it to different filters. Same behavior in Chrome and Edge.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/5489711/156232207-b312f1d2-48f0-4727-a2e6-6740cea91a35.png">

**Comment by bduranc** [comment]
I took a look at this in dev environment. 

Although the search relevance has certainly improved, I still observed one or more cases where other package types are shown (for example, you select "GitHub" from the dropdown but still get NPM packages in the mix too).

![image](https://user-images.githubusercontent.com/31491646/193114419-78eae779-8a37-4445-9edf-01f7c9f20e93.png)

Furthermore, when I actually select the package from the search result it may not always show in the list below. 

This is certainly still the case with more generic named (NPM) packages like "_cli_" or "_log_", but does not appear to impact more specific searches such as "_cli_-box" or "_log_-driver".

![image](https://user-images.githubusercontent.com/31491646/193116744-13ce337b-7bd8-476a-b6a7-8f1c40d7500e.png)

I spoke with @qtomlinson and it appears this selection behavior may be by design in this view. In the workspace view, if you search and select, only the selected component is added. This should probably be tracked separately in another issue.

**Comment by bduranc** [comment]
I can confirm the above appears resolved in dev environment.

The very last point I am told is by design. However, it does now actually populate the list with what I select (albeit along with many other similarly named components from other providers).

**Comment by bduranc** [comment]
> However, it does now actually populate the list with what I select (albeit along with many other similarly named components from other providers).

![image](https://user-images.githubusercontent.com/31491646/211383536-77334a21-334d-4fb5-b79f-2f399643d49e.png)

@qtomlinson is this by design?

**Comment by qtomlinson** [comment]
@bduranc Yes, what you described in the above screen shot is the designed behaviour in the current web ui.  The original issue documented is that the dropdown list below the search text ('abaus') box did not respect the package type selected ('NPMJS').  The dropdown list now only displays the npm related packages, which addressed the issue of 'search suggestions show everything even though filter is set to "NpmJs"'.
 
After a specific search suggestion in the drop down list is clicked, the browse page currently displays all components whose names contain abacus and this is reflect in the url: `https://clearlydefined.io/?sort=releaseDate&sortDesc=true&name=abacus`.   This gives users the ability to explore all the abacus related packages: all versions and the related sources.  If this is undesirable, please track a separate issue if none exists.

**Comment by bduranc** [comment]
@qtomlinson : Alright, just wanted to clarify. Thanks.

@capfei : Do you think we can close this issue then?

**Comment by capfei** [comment]
I think this specific issue appears to be resolved. 

It would be nice if the package name and type I searched for appeared first in the results (exact match first and then similar). If that hasn't been opened yet then I will open an issue.

Thanks for fixing this one!
